# Generated by Django 2.1.12 on 2019-09-21 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EatripApp', '0006_order_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='meal',
            field=models.ForeignKey(default='favourite dish', on_delete=django.db.models.deletion.CASCADE,
                                    to='EatripApp.Meal'),
            preserve_default=False,
        ),
    ]
